name: Angular CI/CD via Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Or match your project version

    - name: Install dependencies
      run: npm install

    - name: Add node_modules/.bin to PATH (for ng)
      run: Add-Content $env:GITHUB_PATH "node_modules/.bin"
      shell: powershell

    - name: Build Angular app
      run: ng build
      shell: pwsh

    - name: Copy build to IIS folder
      run: |
        $source = "$(Get-Location)\dist\test8"
        $destination = "C:\inetpub\wwwroot\FrontEnd\Angular"
        if (Test-Path $destination) {
            Remove-Item "$destination\*" -Recurse -Force
        } else {
            New-Item -ItemType Directory -Path $destination
        }
        Copy-Item -Path "$source\*" -Destination $destination -Recurse
      shell: pwsh
