name: Angular CI/CD via Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Add local ng to PATH
      run: echo "$(pwd)/node_modules/.bin" >> https://github.com/ameer5035464/angular.git

    - name: Build Angular App
      run: ng build
      
    - name: Copy build to IIS folder
      run: |
        $source = "$(pwd)\dist\test8"
        $destination = "C:\inetpub\wwwroot\FrontEnd\Angular"
        if (Test-Path $destination) {
            Remove-Item "$destination\*" -Recurse -Force
        } else {
            New-Item -ItemType Directory -Path $destination
        }
        Copy-Item -Path "$source\*" -Destination $destination -Recurse
      shell: pwsh
